USE leetcode_leaderboard;


INSERT INTO LeetCodeProblems (problem_id, title, difficulty, url) VALUES
(105, 'Reconstruct Itinerary', 'Medium', 'https://leetcode.com/problems/reconstruct-itinerary/'),
(106, 'Construct Binary Tree from Inorder and Postorder Traversal', 'Medium', 'https://leetcode.com/problems/construct-binary-tree-from-inorder-and-postorder-traversal/'),
(107, 'Binary Tree Level Order Traversal II', 'Medium', 'https://leetcode.com/problems/binary-tree-level-order-traversal-ii/'),
(108, 'Convert Sorted Array to Binary Search Tree', 'Easy', 'https://leetcode.com/problems/convert-sorted-array-to-binary-search-tree/'),
(109, 'Convert Sorted List to Binary Search Tree', 'Medium', 'https://leetcode.com/problems/convert-sorted-list-to-binary-search-tree/'),
(110, 'Balanced Binary Tree', 'Easy', 'https://leetcode.com/problems/balanced-binary-tree/'),
(111, 'Minimum Depth of Binary Tree', 'Easy', 'https://leetcode.com/problems/minimum-depth-of-binary-tree/'),
(112, 'Path Sum', 'Easy', 'https://leetcode.com/problems/path-sum/'),
(113, 'Path Sum II', 'Medium', 'https://leetcode.com/problems/path-sum-ii/'),
(114, 'Flatten Binary Tree to Linked List', 'Medium', 'https://leetcode.com/problems/flatten-binary-tree-to-linked-list/'),
(115, 'Distinct Subsequences', 'Hard', 'https://leetcode.com/problems/distinct-subsequences/'),
(116, 'Populating Next Right Pointers in Each Node', 'Medium', 'https://leetcode.com/problems/populating-next-right-pointers-in-each-node/'),
(117, 'Populating Next Right Pointers in Each Node II', 'Medium', 'https://leetcode.com/problems/populating-next-right-pointers-in-each-node-ii/'),
(118, 'Pascals Triangle', 'Easy', 'https://leetcode.com/problems/pascals-triangle/'),
(119, 'Pascals Triangle II', 'Easy', 'https://leetcode.com/problems/pascals-triangle-ii/'),
(120, 'Triangle', 'Medium', 'https://leetcode.com/problems/triangle/'),
(121, 'Best Time to Buy and Sell Stock', 'Easy', 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock/'),
(122, 'Best Time to Buy and Sell Stock II', 'Medium', 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock-ii/'),
(123, 'Best Time to Buy and Sell Stock III', 'Hard', 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock-iii/'),
(124, 'Binary Tree Maximum Path Sum', 'Hard', 'https://leetcode.com/problems/binary-tree-maximum-path-sum/'),
(125, 'Valid Palindrome', 'Easy', 'https://leetcode.com/problems/valid-palindrome/'),
(126, 'Word Ladder II', 'Hard', 'https://leetcode.com/problems/word-ladder-ii/'),
(127, 'Word Ladder', 'Hard', 'https://leetcode.com/problems/word-ladder/'),
(128, 'Longest Consecutive Sequence', 'Hard', 'https://leetcode.com/problems/longest-consecutive-sequence/'),
(129, 'Sum Root to Leaf Numbers', 'Easy', 'https://leetcode.com/problems/sum-root-to-leaf-numbers/'),
(130, 'Surrounded Regions', 'Medium', 'https://leetcode.com/problems/surrounded-regions/'),
(131, 'Palindrome Partitioning', 'Medium', 'https://leetcode.com/problems/palindrome-partitioning/'),
(132, 'Palindrome Partitioning II', 'Hard', 'https://leetcode.com/problems/palindrome-partitioning-ii/'),
(133, 'Clone Graph', 'Medium', 'https://leetcode.com/problems/clone-graph/'),
(134, 'Gas Station', 'Medium', 'https://leetcode.com/problems/gas-station/'),
(135, 'Candy', 'Hard', 'https://leetcode.com/problems/candy/'),
(136, 'Single Number', 'Easy', 'https://leetcode.com/problems/single-number/'),
(137, 'Single Number II', 'Medium', 'https://leetcode.com/problems/single-number-ii/'),
(138, 'Copy List with Random Pointer', 'Hard', 'https://leetcode.com/problems/copy-list-with-random-pointer/'),
(139, 'Word Break', 'Medium', 'https://leetcode.com/problems/word-break/'),
(140, 'Word Break II', 'Hard', 'https://leetcode.com/problems/word-break-ii/'),
(141, 'Linked List Cycle', 'Easy', 'https://leetcode.com/problems/linked-list-cycle/'),
(142, 'Linked List Cycle II', 'Medium', 'https://leetcode.com/problems/linked-list-cycle-ii/'),
(143, 'Reorder List', 'Medium', 'https://leetcode.com/problems/reorder-list/'),
(144, 'Binary Tree Preorder Traversal', 'Easy', 'https://leetcode.com/problems/binary-tree-preorder-traversal/'),
(145, 'Binary Tree Postorder Traversal', 'Easy', 'https://leetcode.com/problems/binary-tree-postorder-traversal/'),
(146, 'LRU Cache', 'Medium', 'https://leetcode.com/problems/lru-cache/'),
(147, 'Insertion Sort List', 'Medium', 'https://leetcode.com/problems/insertion-sort-list/'),
(148, 'Sort List', 'Medium', 'https://leetcode.com/problems/sort-list/'),
(149, 'Max Points on a Line', 'Hard', 'https://leetcode.com/problems/max-points-on-a-line/'),
(150, 'Evaluate Reverse Polish Notation', 'Medium', 'https://leetcode.com/problems/evaluate-reverse-polish-notation/'),
(151, 'Reverse Words in a String', 'Medium', 'https://leetcode.com/problems/reverse-words-in-a-string/'),
(152, 'Maximum Product Subarray', 'Medium', 'https://leetcode.com/problems/maximum-product-subarray/'),
(153, 'Find Minimum in Rotated Sorted Array', 'Medium', 'https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/'),
(154, 'Find Minimum in Rotated Sorted Array II', 'Hard', 'https://leetcode.com/problems/find-minimum-in-rotated-sorted-array-ii/'),
(155, 'Min Stack', 'Easy', 'https://leetcode.com/problems/min-stack/'),
(156, 'Binary Tree Upside Down', 'Medium', 'https://leetcode.com/problems/binary-tree-upside-down/'),
(157, 'Read N Characters Given Read4 II - Call multiple times', 'Hard', 'https://leetcode.com/problems/read-n-characters-given-read4-ii-call-multiple-times/'),
(158, 'Read N Characters Given Read4', 'Easy', 'https://leetcode.com/problems/read-n-characters-given-read4/'),
(159, 'Longest Substring with At Most Two Distinct Characters', 'Medium', 'https://leetcode.com/problems/longest-substring-with-at-most-two-distinct-characters/'),
(160, 'Intersection of Two Linked Lists', 'Easy', 'https://leetcode.com/problems/intersection-of-two-linked-lists/'),
(161, 'One Edit Distance', 'Medium', 'https://leetcode.com/problems/one-edit-distance/'),
(162, 'Find Peak Element', 'Medium', 'https://leetcode.com/problems/find-peak-element/'),
(163, 'Missing Ranges', 'Easy', 'https://leetcode.com/problems/missing-ranges/'),
(164, 'Maximum Gap', 'Hard', 'https://leetcode.com/problems/maximum-gap/'),
(165, 'Compare Version Numbers', 'Medium', 'https://leetcode.com/problems/compare-version-numbers/'),
(166, 'Fraction to Recurring Decimal', 'Medium', 'https://leetcode.com/problems/fraction-to-recurring-decimal/'),
(167, 'Two Sum II - Input Array Is Sorted', 'Easy', 'https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/'),
(168, 'Excel Sheet Column Title', 'Easy', 'https://leetcode.com/problems/excel-sheet-column-title/'),
(169, 'Majority Element', 'Easy', 'https://leetcode.com/problems/majority-element/'),
(170, 'Two Sum III - Data structure design', 'Easy', 'https://leetcode.com/problems/two-sum-iii-data-structure-design/'),
(171, 'Excel Sheet Column Number', 'Easy', 'https://leetcode.com/problems/excel-sheet-column-number/'),
(172, 'Factorial Trailing Zeroes', 'Easy', 'https://leetcode.com/problems/factorial-trailing-zeroes/'),
(173, 'Binary Search Tree Iterator', 'Medium', 'https://leetcode.com/problems/binary-search-tree-iterator/'),
(174, 'Dungeon Game', 'Hard', 'https://leetcode.com/problems/dungeon-game/'),
(175, 'Combine Two Tables', 'Easy', 'https://leetcode.com/problems/combine-two-tables/'),
(176, 'Second Highest Salary', 'Medium', 'https://leetcode.com/problems/second-highest-salary/'),
(177, 'Nth Highest Salary', 'Hard', 'https://leetcode.com/problems/nth-highest-salary/'),
(178, 'Rank Scores', 'Medium', 'https://leetcode.com/problems/rank-scores/'),
(179, 'Largest Number', 'Medium', 'https://leetcode.com/problems/largest-number/');