USE leetcode_leaderboard;

INSERT INTO LeetCodeProblems (problem_id, title, difficulty, url) VALUES
(1, 'Two Sum', 'Easy', 'https://leetcode.com/problems/two-sum/'),
(2, 'Add Two Numbers', 'Medium', 'https://leetcode.com/problems/add-two-numbers/'),
(3, 'Longest Substring Without Repeating Characters', 'Medium', 'https://leetcode.com/problems/longest-substring-without-repeating-characters/'),
(4, 'Median of Two Sorted Arrays', 'Hard', 'https://leetcode.com/problems/median-of-two-sorted-arrays/'),
(5, 'Reverse Integer', 'Easy', 'https://leetcode.com/problems/reverse-integer/'),
(6, 'Palindrome Number', 'Easy', 'https://leetcode.com/problems/palindrome-number/'),
(7, 'Regular Expression Matching', 'Hard', 'https://leetcode.com/problems/regular-expression-matching/'),
(8, 'Container With Most Water', 'Medium', 'https://leetcode.com/problems/container-with-most-water/'),
(9, '3Sum', 'Medium', 'https://leetcode.com/problems/3sum/'),
(10, 'Letter Combinations of a Phone Number', 'Medium', 'https://leetcode.com/problems/letter-combinations-of-a-phone-number/'),
(11, 'Valid Parentheses', 'Easy', 'https://leetcode.com/problems/valid-parentheses/'),
(12, 'Merge Two Sorted Lists', 'Easy', 'https://leetcode.com/problems/merge-two-sorted-lists/'),
(13, 'Generate Parentheses', 'Medium', 'https://leetcode.com/problems/generate-parentheses/'),
(14, 'Swap Nodes in Pairs', 'Medium', 'https://leetcode.com/problems/swap-nodes-in-pairs/'),
(15, 'Remove Duplicates from Sorted Array', 'Easy', 'https://leetcode.com/problems/remove-duplicates-from-sorted-array/'),
(16, 'Search Insert Position', 'Easy', 'https://leetcode.com/problems/search-insert-position/'),
(17, 'Longest Common Prefix', 'Easy', 'https://leetcode.com/problems/longest-common-prefix/'),
(18, 'Climbing Stairs', 'Easy', 'https://leetcode.com/problems/climbing-stairs/'),
(19, 'Simplify Path', 'Medium', 'https://leetcode.com/problems/simplify-path/'),
(20, 'Maximum Subarray', 'Easy', 'https://leetcode.com/problems/maximum-subarray/'),
(21, 'Find Minimum in Rotated Sorted Array', 'Medium', 'https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/'),
(22, 'Search in Rotated Sorted Array', 'Medium', 'https://leetcode.com/problems/search-in-rotated-sorted-array/'),
(23, 'String to Integer (atoi)', 'Medium', 'https://leetcode.com/problems/string-to-integer-atoi/'),
(24, 'Implement strStr()', 'Easy', 'https://leetcode.com/problems/implement-strstr/'),
(25, 'Divide Two Integers', 'Medium', 'https://leetcode.com/problems/divide-two-integers/'),
(26, 'Substr with Concatenation of All Words', 'Hard', 'https://leetcode.com/problems/substring-with-concatenation-of-all-words/'),
(27, 'Multiply Strings', 'Medium', 'https://leetcode.com/problems/multiply-strings/'),
(28, 'Next Permutation', 'Medium', 'https://leetcode.com/problems/next-permutation/'),
(29, 'Search a 2D Matrix', 'Medium', 'https://leetcode.com/problems/search-a-2d-matrix/'),
(30, 'Count and Say', 'Easy', 'https://leetcode.com/problems/count-and-say/'),
(31, 'Spiral Matrix', 'Medium', 'https://leetcode.com/problems/spiral-matrix/'),
(32, 'Jump Game', 'Medium', 'https://leetcode.com/problems/jump-game/'),
(33, 'Permutations', 'Medium', 'https://leetcode.com/problems/permutations/'),
(34, 'Rotate Image', 'Medium', 'https://leetcode.com/problems/rotate-image/'),
(35, 'Group Anagrams', 'Medium', 'https://leetcode.com/problems/group-anagrams/'),
(36, 'Pow(x, n)', 'Medium', 'https://leetcode.com/problems/powx-n/'),
(37, 'N-Queens', 'Hard', 'https://leetcode.com/problems/n-queens/'),
(38, 'Product of Array Except Self', 'Medium', 'https://leetcode.com/problems/product-of-array-except-self/'),
(39, 'Find the Duplicate Number', 'Medium', 'https://leetcode.com/problems/find-the-duplicate-number/'),
(40, 'Top K Frequent Elements', 'Medium', 'https://leetcode.com/problems/top-k-frequent-elements/'),
(41, 'Sliding Window Maximum', 'Hard', 'https://leetcode.com/problems/sliding-window-maximum/'),
(42, 'Word Ladder', 'Hard', 'https://leetcode.com/problems/word-ladder/'),
(43, 'Minimum Window Substring', 'Hard', 'https://leetcode.com/problems/minimum-window-substring/'),
(44, 'Subsets', 'Medium', 'https://leetcode.com/problems/subsets/'),
(45, 'Combination Sum', 'Medium', 'https://leetcode.com/problems/combination-sum/'),
(46, 'Unique Paths', 'Medium', 'https://leetcode.com/problems/unique-paths/'),
(47, 'Decode Ways', 'Medium', 'https://leetcode.com/problems/decode-ways/'),
(48, 'Sort Colors', 'Medium', 'https://leetcode.com/problems/sort-colors/'),
(49, 'Binary Tree Level Order Traversal', 'Medium', 'https://leetcode.com/problems/binary-tree-level-order-traversal/'),
(50, 'Lowest Common Ancestor of a Binary Tree', 'Medium', 'https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/'),
(51, 'Convert Sorted Array to Binary Search Tree', 'Easy', 'https://leetcode.com/problems/convert-sorted-array-to-binary-search-tree/'),
(52, 'Binary Tree Inorder Traversal', 'Easy', 'https://leetcode.com/problems/binary-tree-inorder-traversal/'),
(53, 'Serialize and Deserialize Binary Tree', 'Hard', 'https://leetcode.com/problems/serialize-and-deserialize-binary-tree/'),
(54, 'Subtree of Another Tree', 'Easy', 'https://leetcode.com/problems/subtree-of-another-tree/'),
(55, 'Maximum Depth of Binary Tree', 'Easy', 'https://leetcode.com/problems/maximum-depth-of-binary-tree/'),
(56, 'Path Sum', 'Easy', 'https://leetcode.com/problems/path-sum/'),
(57, 'Balanced Binary Tree', 'Easy', 'https://leetcode.com/problems/balanced-binary-tree/'),
(58, 'Binary Tree Maximum Path Sum', 'Hard', 'https://leetcode.com/problems/binary-tree-maximum-path-sum/'),
(59, 'Binary Tree Zigzag Level Order Traversal', 'Medium', 'https://leetcode.com/problems/binary-tree-zigzag-level-order-traversal/'),
(60, 'Flatten Binary Tree to Linked List', 'Medium', 'https://leetcode.com/problems/flatten-binary-tree-to-linked-list/'),
(61, 'Kth Smallest Element in a BST', 'Medium', 'https://leetcode.com/problems/kth-smallest-element-in-a-bst/'),
(62, 'Sum Root to Leaf Numbers', 'Easy', 'https://leetcode.com/problems/sum-root-to-leaf-numbers/'),
(63, 'Merge k Sorted Lists', 'Hard', 'https://leetcode.com/problems/merge-k-sorted-lists/'),
(64, 'Remove Nth Node From End of List', 'Medium', 'https://leetcode.com/problems/remove-nth-node-from-end-of-list/'),
(65, 'Reverse Linked List', 'Easy', 'https://leetcode.com/problems/reverse-linked-list/'),
(66, 'Linked List Cycle', 'Easy', 'https://leetcode.com/problems/linked-list-cycle/'),
(67, 'Intersection of Two Linked Lists', 'Easy', 'https://leetcode.com/problems/intersection-of-two-linked-lists/'),
(68, 'Add Two Numbers II', 'Medium', 'https://leetcode.com/problems/add-two-numbers-ii/'),
(69, 'Remove Duplicates from Sorted List', 'Easy', 'https://leetcode.com/problems/remove-duplicates-from-sorted-list/'),
(70, 'Copy List with Random Pointer', 'Hard', 'https://leetcode.com/problems/copy-list-with-random-pointer/'),
(71, 'Linked List Random Node', 'Medium', 'https://leetcode.com/problems/linked-list-random-node/'),
(72, 'Longest Palindromic Substring', 'Medium', 'https://leetcode.com/problems/longest-palindromic-substring/'),
(73, 'Count of Smaller Numbers After Self', 'Hard', 'https://leetcode.com/problems/count-of-smaller-numbers-after-self/'),
(74, 'Largest Rectangle in Histogram', 'Hard', 'https://leetcode.com/problems/largest-rectangle-in-histogram/'),
(75, 'Trapping Rain Water', 'Hard', 'https://leetcode.com/problems/trapping-rain-water/'),
(76, 'Merge Intervals', 'Medium', 'https://leetcode.com/problems/merge-intervals/'),
(77, 'Insert Interval', 'Hard', 'https://leetcode.com/problems/insert-interval/'),
(78, 'Meeting Rooms II', 'Medium', 'https://leetcode.com/problems/meeting-rooms-ii/'),
(79, 'Basic Calculator', 'Hard', 'https://leetcode.com/problems/basic-calculator/'),
(80, 'Palindrome Partitioning', 'Medium', 'https://leetcode.com/problems/palindrome-partitioning/'),
(81, 'Distinct Subsequences', 'Hard', 'https://leetcode.com/problems/distinct-subsequences/'),
(82, 'Largest Divisible Subset', 'Medium', 'https://leetcode.com/problems/largest-divisible-subset/'),
(83, 'Combination Sum IV', 'Medium', 'https://leetcode.com/problems/combination-sum-iv/'),
(84, 'Reverse Nodes in k-Group', 'Hard', 'https://leetcode.com/problems/reverse-nodes-in-k-group/'),
(85, 'Maximal Rectangle', 'Hard', 'https://leetcode.com/problems/maximal-rectangle/'),
(86, 'Word Break', 'Medium', 'https://leetcode.com/problems/word-break/'),
(87, 'Word Break II', 'Hard', 'https://leetcode.com/problems/word-break-ii/'),
(88, 'Basic Calculator II', 'Medium', 'https://leetcode.com/problems/basic-calculator-ii/'),
(89, 'Binary Search Tree Iterator', 'Medium', 'https://leetcode.com/problems/binary-search-tree-iterator/'),
(90, 'Search in Rotated Sorted Array II', 'Hard', 'https://leetcode.com/problems/search-in-rotated-sorted-array-ii/'),
(91, 'N-Queens II', 'Hard', 'https://leetcode.com/problems/n-queens-ii/'),
(92, 'Wildcard Matching', 'Hard', 'https://leetcode.com/problems/wildcard-matching/'),
(93, 'Find Peak Element', 'Medium', 'https://leetcode.com/problems/find-peak-element/'),
(94, 'Design Tic-Tac-Toe', 'Medium', 'https://leetcode.com/problems/design-tic-tac-toe/'),
(95, 'Split Array into Consecutive Subsequences', 'Medium', 'https://leetcode.com/problems/split-array-into-consecutive-subsequences/'),
(96, 'Count of Smaller Numbers After Self', 'Hard', 'https://leetcode.com/problems/count-of-smaller-numbers-after-self/'),
(97, 'Word Ladder II', 'Hard', 'https://leetcode.com/problems/word-ladder-ii/'),
(98, 'Trapping Rain Water II', 'Hard', 'https://leetcode.com/problems/trapping-rain-water-ii/'),
(99, 'Max Points on a Line', 'Hard', 'https://leetcode.com/problems/max-points-on-a-line/'),
(100, 'Largest Rectangle in Histogram', 'Hard', 'https://leetcode.com/problems/largest-rectangle-in-histogram/'),
(101, 'Remove Covered Intervals', 'Medium', 'https://leetcode.com/problems/remove-covered-intervals/'),
(102, 'Longest Common Subsequence', 'Medium', 'https://leetcode.com/problems/longest-common-subsequence/'),
(103, 'All Paths From Source to Target', 'Medium', 'https://leetcode.com/problems/all-paths-from-source-to-target/'),
(104, 'Largest Rectangle in Histogram', 'Hard', 'https://leetcode.com/problems/largest-rectangle-in-histogram/');
